name: Web Chromatic E2E

on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'Test scope'
        required: true
        type: choice
        default: 'smoke'
        options:
          - smoke
          - full

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Cypress ${{ inputs.scope == 'smoke' && 'Smoke' || 'Full' }} tests
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        containers: ${{ fromJSON(inputs.scope == 'smoke' && '[1, 2, 3, 4, 5]' || '[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]') }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/cypress
        with:
          secrets: ${{ toJSON(secrets) }}
          spec: ${{ inputs.scope == 'smoke' && 'cypress/e2e/smoke/*.cy.js' || 'cypress/e2e/smoke/*.cy.js,cypress/e2e/regression/*.cy.js,cypress/e2e/safe-apps/*.cy.js' }}
          group: 'Chromatic E2E'
          tag: 'chromatic-e2e'
          chromatic: 'true'
          container-index: ${{ matrix.containers }}

  chromatic:
    needs: [e2e]
    if: always() && needs.e2e.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/yarn

      - uses: actions/download-artifact@v7
        with:
          pattern: chromatic-archives-*
          merge-multiple: true
          path: apps/web/cypress/downloads

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          cypress: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/web
        env:
          CHROMATIC_ARCHIVE_LOCATION: ./cypress/downloads
